[package]
name = "tests-build"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8.20"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.96"

[build-dependencies]
glob = "0.3.2"